# Generated by Django 5.0.6 on 2024-06-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('dob_me', models.DateField(null=True)),
                ('about', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
